# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Robert Rose
title: 3rd year Computer Science Student
email: robertbenrose@gmail.com
website: https://robbenrose.github.io/Resume-Website/

# Social links
github_username:  robbenrose
linkedin_username: Robert Rose

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Robert and I'm a third year Computer Science student at the University of Manitoba.

  Languages I have experience working with are: <mark>Java</mark> and <mark>C</mark> and <mark>Markdown<mark>
  
  Frameworks and Tools I have used include: <mark>GitHub<mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Computer Science and learning new skills, some of my other interests and hobbies are:
   - Jogging
   - Beginner Powerlifting
   - D&D 5th edition

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
